### ISSUE TITLE
Cannot build abieos - errors in abieos.hpp

### ISSUE THREAD

**Issue by gravitt8460** [EOSIO/abieos#3]
I am working on an IoT device to sign and submit transactions to EOS nodes. I am trying to build abieos and get the following errors on "make":

$ make
Scanning dependencies of target test-sanitize
[ 12%] Building CXX object CMakeFiles/test-sanitize.dir/src/abieos.cpp.o
In file included from /home/max/dev/eosdev/abieos/src/abieos.cpp:4:0:
/home/max/dev/eosdev/abieos/src/abieos.hpp: In function ‘bool abieos::json_to_native(abieos::name&, abieos::json_to_native_state&, abieos::event_type, bool)’:
/home/max/dev/eosdev/abieos/src/abieos.hpp:563:97: warning: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 5 has type ‘uint64_t {aka long unsigned int}’ [-Wformat=]
                    state.received_data.value_string.c_str(), obj.value, std::string{obj}.c_str());
                                                              ~~~~~~~~~                          ^
/home/max/dev/eosdev/abieos/src/abieos.hpp: In function ‘bool abieos::json_to_bin(abieos::name*, abieos::json_to_bin_state&, const abieos::abi_type*, abieos::event_type, bool)’:
/home/max/dev/eosdev/abieos/src/abieos.hpp:574:97: warning: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 5 has type ‘uint64_t {aka long unsigned int}’ [-Wformat=]
                    state.received_data.value_string.c_str(), obj.value, std::string{obj}.c_str());
                                                              ~~~~~~~~~                          ^
/home/max/dev/eosdev/abieos/src/abieos.hpp: At global scope:
/home/max/dev/eosdev/abieos/src/**abieos.hpp:957:15: error: declaration of ‘abieos::name abieos::action_def::name’ [-fpermissive]
     name name{};**
               ^
/home/max/dev/eosdev/abieos/src/abieos.hpp:541:8: error: changes meaning of ‘name’ from ‘struct abieos::name’ [-fpermissive]
 struct name {
        ^~~~
/home/max/dev/eosdev/abieos/src/abieos.hpp:970:15: error: declaration of ‘abieos::name abieos::table_def::name’ [-fpermissive]
     name name{};
               ^
/home/max/dev/eosdev/abieos/src/abieos.hpp:541:8: error: changes meaning of ‘name’ from ‘struct abieos::name’ [-fpermissive]
 struct name {
        ^~~~
/home/max/dev/eosdev/abieos/src/abieos.hpp: In function ‘bool abieos::receive_event(abieos::json_to_native_state&, abieos::event_type, bool)’:
/home/max/dev/eosdev/abieos/src/abieos.hpp:1205:37: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘abieos::event_type’ [-Wformat=]
         printf("(event %d)\n", event);
                                     ^
/home/max/dev/eosdev/abieos/src/abieos.hpp: At global scope:
/home/max/dev/eosdev/abieos/src/abieos.hpp:1372:34: error: declaration of ‘const abieos::struct_def* abieos::abi_type::struct_def’ [-fpermissive]
     const struct_def* struct_def{};
                                  ^
/home/max/dev/eosdev/abieos/src/abieos.hpp:943:8: error: changes meaning of ‘struct_def’ from ‘struct abieos::struct_def’ [-fpermissive]
 struct struct_def {
        ^~~~~~~~~~

**Comment by tbfleming** [comment]
Which compiler and version?

**Comment by gravitt8460** [comment]
max@max-think-pad:~/dev/eosdev/abieos$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper

OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu
7.2.0-8ubuntu3.2' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs
--enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr
--with-gcc-major-version-only --program-suffix=-7
--program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id
--libexecdir=/usr/lib --wit
hout-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls
--with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug
--enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new
--enable-gnu-unique-object --disable-vtable-verify --enable-libmpx
--enable-plugin --enable-default-pie --with-system-zlib
--with-target-system-zlib --enable-objc
-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686
--with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib
--with-tune=generic --enable-offload-targets=nvptx-none
--without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu
--host=x86_64-linux-gnu --target=x86_64-linux-gnu

Thread model: posix


gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3.2)

max@max-think-pad:~/dev/eosdev/abieos$ make -v

GNU Make 4.1
Built for x86_64-pc-linux-gnu

**Comment by gravitt8460** [comment]
I have a bit more generalized question as I look through this project. I am working on an IoT device, and it is too small to run node.js. It can only run python and C++. The device will have the keys locally. Is this project dependent on eosjs2?

**Comment by zero2pi** [comment]
same problem !!!! does not compile with gcc -std=c++11 or c++14 and gives a lot of error. but when I try 
admin$ g++ -std=c++1z src/abieos.cpp
In file included from src/abieos.cpp:4:
src/abieos.hpp:1066:20: error: constexpr variable 'num_fields' must be initialized by a
      constant expression
    constexpr auto num_fields = ([&]() constexpr {
                   ^            ~~~~~~~~~~~~~~~~~~
src/abieos.hpp:1080:54: note: in instantiation of function template specialization
      'abieos::create_native_field_serializers<abieos::abi_def>' requested here
inline constexpr auto native_field_serializers_for = create_native_field_serializers<T>();
                                                     ^
src/abieos.hpp:1110:77: note: in instantiation of variable template specialization
      'abieos::native_field_serializers_for' requested here
            printf("%*s{ %d fields\n", int(state.stack.size() * 4), "", int(native_fi...
                                                                            ^
src/abieos.hpp:1038:26: note: in instantiation of function template specialization
      'abieos::bin_to_native<abieos::abi_def>' requested here
        return ::abieos::bin_to_native(*reinterpret_cast<T*>(v), state, start);
                         ^
src/abieos.hpp:1046:47: note: in instantiation of member function
      'abieos::native_serializer_impl<abieos::abi_def>::bin_to_native' requested here
inline constexpr auto native_serializer_for = native_serializer_impl<T>{};
                                              ^
src/abieos.cpp:102:14: note: in instantiation of function template specialization
      'abieos::json_to_native<abieos::abi_def>' requested here
        if (!json_to_native(def, abi))
             ^
src/abieos.hpp:1068:37: note: unimplemented constexpr lambda feature: can not evaluate lambda
      expressions with captures (coming soon!)
        for_each_field((T*)nullptr, [&](auto, auto) { ++num_fields; });
                                    ^
src/abieos.hpp:1066:34: note: in call to '&[&] ()     {
        int num_fields = 0;
        for_each_field((abieos::abi_def *)nullptr, [&] (type-parameter-0-0, type-parameter-0-1)             {
                ++num_fields;
            }
);
        return num_fields;
    }
->operator()()'
    constexpr auto num_fields = ([&]() constexpr {
                                 ^
src/abieos.hpp:1071:41: error: non-type template argument is not a constant expression
    std::array<native_field_serializer, num_fields> fields;
                                        ^~~~~~~~~~
src/abieos.hpp:1071:41: note: initializer of 'num_fields' is not a constant expression
src/abieos.hpp:1066:20: note: declared here
    constexpr auto num_fields = ([&]() constexpr {
                   ^
2 errors generated.
                   ^            ~~~~~~~~~~~~~~~~~~

I get two errors regarding constexpr when I am trying with -std=c++1z.
can we have a small set of instruction to understand how to build it ?

**Comment by tbfleming** [comment]
I added support for Ubuntu 16.04 with gcc 8.1.0 and added build instructions for that combination to the readme. gcc 7 and earlier are too old.

**Comment by zero2pi** [comment]
builds perfectly on ubuntu now. But it wont work on mac maybe you can look into that as well.Thanks

**Comment by tbfleming** [comment]
I developed it on OSX. It builds with clang 4.0.1 (homebrew).

**Comment by zero2pi** [comment]
==================================My MAC==================================
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

================================= Error=============================
make
Scanning dependencies of target test-sanitize
[ 12%] Building CXX object CMakeFiles/test-sanitize.dir/src/test.cpp.o
[ 25%] Building CXX object CMakeFiles/test-sanitize.dir/src/abieos.cpp.o
In file included from /Users/admin/Documents/playground/eos_tools/abieos/src/abieos.cpp:4:
/Users/admin/Documents/playground/eos_tools/abieos/src/abieos.hpp:1066:20: error: 
      constexpr variable 'num_fields' must be initialized by a constant
      expression
    constexpr auto num_fields = ([&]() constexpr {
                   ^            ~~~~~~~~~~~~~~~~~~
/Users/admin/Documents/playground/eos_tools/abieos/src/abieos.hpp:1080:54: note: 
      in instantiation of function template specialization
      'abieos::create_native_field_serializers<abieos::abi_def>' requested here
inline constexpr auto native_field_serializers_for = create_native_field...
                                                     ^
/Users/admin/Documents/playground/eos_tools/abieos/src/abieos.hpp:1110:77: note: 
      in instantiation of variable template specialization
      'abieos::native_field_serializers_for' requested here
  ...printf("%*s{ %d fields\n", int(state.stack.size() * 4), "", int(native_f...
                                                                     ^
/Users/admin/Documents/playground/eos_tools/abieos/src/abieos.hpp:1038:26: note: 
      in instantiation of function template specialization
      'abieos::bin_to_native<abieos::abi_def>' requested here
        return ::abieos::bin_to_native(*reinterpret_cast<T*>(v), state, start);
                         ^
/Users/admin/Documents/playground/eos_tools/abieos/src/abieos.hpp:1046:47: note: 
      in instantiation of member function
      'abieos::native_serializer_impl<abieos::abi_def>::bin_to_native' requested
      here
inline constexpr auto native_serializer_for = native_serializer_impl<T>{};
                                              ^
/Users/admin/Documents/playground/eos_tools/abieos/src/abieos.cpp:102:14: note: 
      in instantiation of function template specialization
      'abieos::json_to_native<abieos::abi_def>' requested here
        if (!json_to_native(def, abi))
             ^
/Users/admin/Documents/playground/eos_tools/abieos/src/abieos.hpp:1068:37: note: 
      unimplemented constexpr lambda feature: can not evaluate lambda
      expressions with captures (coming soon!)
        for_each_field((T*)nullptr, [&](auto, auto) { ++num_fields; });
                                    ^
/Users/admin/Documents/playground/eos_tools/abieos/src/abieos.hpp:1066:34: note: 
      in call to '&[&] ()     {
        int num_fields = 0;
        for_each_field((abieos::abi_def *)nullptr, [&] (type-parameter-0-0, type-parameter-0-1)             {
                ++num_fields;
            }
);
        return num_fields;
    }
->operator()()'
    constexpr auto num_fields = ([&]() constexpr {
                                 ^
/Users/admin/Documents/playground/eos_tools/abieos/src/abieos.hpp:1071:41: error: 
      non-type template argument is not a constant expression
    std::array<native_field_serializer, num_fields> fields;
                                        ^~~~~~~~~~
/Users/admin/Documents/playground/eos_tools/abieos/src/abieos.hpp:1071:41: note: 
      initializer of 'num_fields' is not a constant expression
/Users/admin/Documents/playground/eos_tools/abieos/src/abieos.hpp:1066:20: note: 
      declared here
    constexpr auto num_fields = ([&]() constexpr {
                   ^
2 errors generated.
==============================================

**Comment by tbfleming** [comment]
```
constexpr variable 'num_fields' must be initialized by a constant expression
```

Either the compiler is too old, or it's ignoring this cmake directive:

```
set(CMAKE_CXX_STANDARD 17)
```

**Comment by tbfleming** [comment]
Correction from my comment above. abios builds on OSX with:

```
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

It looks like `Apple LLVM version 9.0.0` may be too old.

**Comment by gravitt8460** [comment]
I upgraded to gcc 8,.1 and I still get the same error.

```
gcc --version
gcc (GCC) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ make
[ 12%] Building CXX object CMakeFiles/test-sanitize.dir/src/abieos.cpp.o
In file included from /home/max/dev/eosdev/abieos/src/abieos.cpp:4:
/home/max/dev/eosdev/abieos/src/abieos.hpp:957:15: error: declaration of ‘abieos::name abieos::action_def::name’ [-fpermissive]
     name name{};
               ^
/home/max/dev/eosdev/abieos/src/abieos.hpp:541:8: error: changes meaning of ‘name’ from ‘struct abieos::name’ [-fpermissive]
 struct name {
        ^~~~
/home/max/dev/eosdev/abieos/src/abieos.hpp:970:15: error: declaration of ‘abieos::name abieos::table_def::name’ [-fpermissive]
     name name{};
               ^
/home/max/dev/eosdev/abieos/src/abieos.hpp:541:8: error: changes meaning of ‘name’ from ‘struct abieos::name’ [-fpermissive]
 struct name {
        ^~~~
/home/max/dev/eosdev/abieos/src/abieos.hpp:1372:34: error: declaration of ‘const abieos::struct_def* abieos::abi_type::struct_def’ [-fpermissive]
     const struct_def* struct_def{};
                                  ^
/home/max/dev/eosdev/abieos/src/abieos.hpp:943:8: error: changes meaning of ‘struct_def’ from ‘struct abieos::struct_def’ [-fpermissive]
 struct struct_def {
        ^~~~~~~~~~
CMakeFiles/test-sanitize.dir/build.make:75: recipe for target 'CMakeFiles/test-sanitize.dir/src/abieos.cpp.o' failed
make[2]: *** [CMakeFiles/test-sanitize.dir/src/abieos.cpp.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/test-sanitize.dir/all' failed
make[1]: *** [CMakeFiles/test-sanitize.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
**
```
